#!/bin/bash

. $CMSSW_BASE/src/UserCode/Stop4Body-nanoAOD/Macros/setupPaths.sh

touch $JSON_PATH/tmp.json
rm    $JSON_PATH/*.json

if [ ${YEAR} == 2015 ]; then
 # Make a JSON for all MC except signal
 mergeJSONs $JSON_PATH/Orig/Wjets.json         $JSON_PATH/Orig/Wjets_*.json
 mergeJSONs $JSON_PATH/backgroundMC.json       $JSON_PATH/Orig/TTbar.json $JSON_PATH/Orig/Wjets.json
 cp         $JSON_PATH/Orig/Wjets.json         $JSON_PATH/Wjets.json
 cp         $JSON_PATH/Orig/TTbar.json         $JSON_PATH/TTbar.json
 #cp         $JSON_PATH/Orig/TTbar_LO.json      $JSON_PATH/TTbar_LO.json
 cp         $JSON_PATH/Orig/TTLep.json         $JSON_PATH/TTLep.json
 mergeJSONs $JSON_PATH/TT_pow.json             $JSON_PATH/Orig/TT_pow.json $JSON_PATH/Orig/TT_pow_backup.json
 mergeJSONs $JSON_PATH/otherMC1.json           $JSON_PATH/Orig/QCD.json $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTW_LO.json $JSON_PATH/Orig/TTZ_LO.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTWToQQ.json $JSON_PATH/Orig/TTZToQQ.json $JSON_PATH/Orig/TTZToLLNuNu.json
 mergeJSONs $JSON_PATH/ttx.json                $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTW_LO.json $JSON_PATH/Orig/TTZ_LO.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTWToQQ.json $JSON_PATH/Orig/TTZToQQ.json $JSON_PATH/Orig/TTZToLLNuNu.json
 cp         $JSON_PATH/Orig/ZInv.json          $JSON_PATH/otherMC2.json
 mergeJSONs $JSON_PATH/otherMC3.json           $JSON_PATH/Orig/VV.json      $JSON_PATH/Orig/SingleTop.json
 cp         $JSON_PATH/Orig/DYJets.json        $JSON_PATH/otherMC4.json
 mergeJSONs $JSON_PATH/otherMC.json            $JSON_PATH/Orig/QCD.json $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTWToQQ.json $JSON_PATH/Orig/TTZToQQ.json $JSON_PATH/Orig/TTZToLLNuNu.json $JSON_PATH/otherMC2.json $JSON_PATH/otherMC3.json $JSON_PATH/otherMC4.json
 mergeJSONs $JSON_PATH/allMC.json              $JSON_PATH/Orig/Wjets.json $JSON_PATH/TT_pow.json $JSON_PATH/TTLep.json $JSON_PATH/otherMC1.json $JSON_PATH/otherMC2.json $JSON_PATH/otherMC3.json $JSON_PATH/otherMC4.json
 mergeJSONs $JSON_PATH/allMCQuick.json         $JSON_PATH/Orig/Wjets.json $JSON_PATH/otherMC1.json $JSON_PATH/otherMC3.json
 #$JSON_PATH/TTLep.json $JSON_PATH/otherMC2.json $JSON_PATH/otherMC4.json

 #Make a JSON with the samples that are to be processed:
 mergeJSONs $JSON_PATH/MC2Process.json         $JSON_PATH/Orig/Wjets.json $JSON_PATH/Orig/TTLep.json $JSON_PATH/TT_pow.json $JSON_PATH/Orig/QCD.json $JSON_PATH/Orig/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTW_LO.json $JSON_PATH/Orig/TTZ_LO.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTWToQQ.json $JSON_PATH/Orig/TTZToQQ.json $JSON_PATH/Orig/TTZToLLNuNu.json

 # Copy the data JSON over, so that all locations are consistent
 cp         $JSON_PATH/Orig/Data.json          $JSON_PATH/
 #mergeJSONs $JSON_PATH/DataLepton.json         $JSON_PATH/Orig/DataSingleElectron.json $JSON_PATH/Orig/DataSingleMuon.json
 cp         $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/DataSingleLepton.json

 # Make a JSON for all PD
 mergeJSONs $JSON_PATH/allPD.json              $JSON_PATH/Orig/PD.json       $JSON_PATH/Orig/PDInj.json

 # Make a JSON for producing the PD
 mergeJSONs $JSON_PATH/makePD.json             $JSON_PATH/Orig/TT_pow.json   $JSON_PATH/Orig/Wjets.json $JSON_PATH/Orig/ZInv.json
 mergeJSONs $JSON_PATH/makePD_Inj_300_270.json $JSON_PATH/makePD.json        $JSON_PATH/Orig/SignalPoints/Sig_300_270.json

 # Make the JSON for synchronization
 mergeJSONs $JSON_PATH/synch.json              $JSON_PATH/Orig/TTbar.json    $JSON_PATH/Orig/SignalPoints/Sig_300_270.json

 # Make the JSONs for plotting
 #mergeJSONs $JSON_PATH/plot2016.json           $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTbar.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_300_270.json
 mergeJSONs $JSON_PATH/plot2016_pow.json       $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TT_pow.json   $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json
 mergeJSONs $JSON_PATH/plot2016_lep.json       $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json
 #mergeJSONs $JSON_PATH/plot2016swap.json           $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTbar.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_300_270.json
 mergeJSONs $JSON_PATH/plot2016swap_pow.json       $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TT_pow.json   $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json
 mergeJSONs $JSON_PATH/plot2016swap_lep.json       $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json

 mergeJSONs $JSON_PATH/plot2016_DM10RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/plot2016swap_DM10RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/plot2016_DM20RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_500_480.json
 mergeJSONs $JSON_PATH/plot2016swap_DM20RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json
 mergeJSONs $JSON_PATH/plot2016_DM30RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_550_520.json
 mergeJSONs $JSON_PATH/plot2016swap_DM30RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json
 mergeJSONs $JSON_PATH/plot2016_DM40RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_550_510.json
 mergeJSONs $JSON_PATH/plot2016swap_DM40RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_550_510.json
 mergeJSONs $JSON_PATH/plot2016_DM50RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_525_475.json
 mergeJSONs $JSON_PATH/plot2016swap_DM50RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_525_475.json
 mergeJSONs $JSON_PATH/plot2016_DM60RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_525_465.json
 mergeJSONs $JSON_PATH/plot2016swap_DM60RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_525_465.json
 mergeJSONs $JSON_PATH/plot2016_DM70RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_525_455.json
 mergeJSONs $JSON_PATH/plot2016swap_DM70RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_525_455.json
 mergeJSONs $JSON_PATH/plot2016_DM80RP.json     $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/Data.json         $JSON_PATH/Orig/SignalPoints/Sig_500_420.json
 mergeJSONs $JSON_PATH/plot2016swap_DM80RP.json $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/DataSingleLepton.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json

 mergeJSONs $JSON_PATH/plot2016_closure.json    $JSON_PATH/otherMC.json       $JSON_PATH/Orig/TTLep.json    $JSON_PATH/Orig/Wjets.json  $JSON_PATH/Orig/AllMCAsData.json  $JSON_PATH/Orig/SignalPoints/Sig_300_270.json

 # Make a JSON for the PU tests
 mergeJSONs $JSON_PATH/puTests.json            $JSON_PATH/Orig/TTLep.json $JSON_PATH/Orig/Data.json

 # Copy the JSON with the info for each deltaM over, so that all locations are consistent
 cp         $JSON_PATH/Orig/DeltaM.json        $JSON_PATH/

 # Make a JSON for each group of signal points with the same stop mass
 mergeJSONs $JSON_PATH/stop250.json            $JSON_PATH/Orig/SignalPoints/Sig_250_170.json $JSON_PATH/Orig/SignalPoints/Sig_250_180.json $JSON_PATH/Orig/SignalPoints/Sig_250_190.json $JSON_PATH/Orig/SignalPoints/Sig_250_200.json $JSON_PATH/Orig/SignalPoints/Sig_250_210.json $JSON_PATH/Orig/SignalPoints/Sig_250_220.json $JSON_PATH/Orig/SignalPoints/Sig_250_230.json $JSON_PATH/Orig/SignalPoints/Sig_250_240.json
 mergeJSONs $JSON_PATH/stop275.json            $JSON_PATH/Orig/SignalPoints/Sig_275_195.json $JSON_PATH/Orig/SignalPoints/Sig_275_205.json $JSON_PATH/Orig/SignalPoints/Sig_275_215.json $JSON_PATH/Orig/SignalPoints/Sig_275_225.json $JSON_PATH/Orig/SignalPoints/Sig_275_235.json $JSON_PATH/Orig/SignalPoints/Sig_275_245.json $JSON_PATH/Orig/SignalPoints/Sig_275_255.json $JSON_PATH/Orig/SignalPoints/Sig_275_265.json
 mergeJSONs $JSON_PATH/stop300.json            $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json
 mergeJSONs $JSON_PATH/stop325.json            $JSON_PATH/Orig/SignalPoints/Sig_325_245.json $JSON_PATH/Orig/SignalPoints/Sig_325_255.json $JSON_PATH/Orig/SignalPoints/Sig_325_265.json $JSON_PATH/Orig/SignalPoints/Sig_325_275.json $JSON_PATH/Orig/SignalPoints/Sig_325_285.json $JSON_PATH/Orig/SignalPoints/Sig_325_295.json $JSON_PATH/Orig/SignalPoints/Sig_325_305.json $JSON_PATH/Orig/SignalPoints/Sig_325_315.json
 mergeJSONs $JSON_PATH/stop350.json            $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json
 mergeJSONs $JSON_PATH/stop375.json            $JSON_PATH/Orig/SignalPoints/Sig_375_295.json $JSON_PATH/Orig/SignalPoints/Sig_375_305.json $JSON_PATH/Orig/SignalPoints/Sig_375_315.json $JSON_PATH/Orig/SignalPoints/Sig_375_325.json $JSON_PATH/Orig/SignalPoints/Sig_375_335.json $JSON_PATH/Orig/SignalPoints/Sig_375_345.json $JSON_PATH/Orig/SignalPoints/Sig_375_355.json $JSON_PATH/Orig/SignalPoints/Sig_375_365.json
 mergeJSONs $JSON_PATH/stop400.json            $JSON_PATH/Orig/SignalPoints/Sig_400_320.json $JSON_PATH/Orig/SignalPoints/Sig_400_330.json $JSON_PATH/Orig/SignalPoints/Sig_400_340.json $JSON_PATH/Orig/SignalPoints/Sig_400_350.json $JSON_PATH/Orig/SignalPoints/Sig_400_360.json $JSON_PATH/Orig/SignalPoints/Sig_400_370.json $JSON_PATH/Orig/SignalPoints/Sig_400_380.json $JSON_PATH/Orig/SignalPoints/Sig_400_390.json
 mergeJSONs $JSON_PATH/stop425.json            $JSON_PATH/Orig/SignalPoints/Sig_425_345.json $JSON_PATH/Orig/SignalPoints/Sig_425_355.json $JSON_PATH/Orig/SignalPoints/Sig_425_365.json $JSON_PATH/Orig/SignalPoints/Sig_425_375.json $JSON_PATH/Orig/SignalPoints/Sig_425_385.json $JSON_PATH/Orig/SignalPoints/Sig_425_395.json $JSON_PATH/Orig/SignalPoints/Sig_425_405.json $JSON_PATH/Orig/SignalPoints/Sig_425_415.json
 mergeJSONs $JSON_PATH/stop450.json            $JSON_PATH/Orig/SignalPoints/Sig_450_370.json $JSON_PATH/Orig/SignalPoints/Sig_450_380.json $JSON_PATH/Orig/SignalPoints/Sig_450_390.json $JSON_PATH/Orig/SignalPoints/Sig_450_400.json $JSON_PATH/Orig/SignalPoints/Sig_450_410.json $JSON_PATH/Orig/SignalPoints/Sig_450_420.json $JSON_PATH/Orig/SignalPoints/Sig_450_430.json $JSON_PATH/Orig/SignalPoints/Sig_450_440.json
 mergeJSONs $JSON_PATH/stop475.json            $JSON_PATH/Orig/SignalPoints/Sig_475_395.json $JSON_PATH/Orig/SignalPoints/Sig_475_405.json $JSON_PATH/Orig/SignalPoints/Sig_475_415.json $JSON_PATH/Orig/SignalPoints/Sig_475_425.json $JSON_PATH/Orig/SignalPoints/Sig_475_435.json $JSON_PATH/Orig/SignalPoints/Sig_475_445.json $JSON_PATH/Orig/SignalPoints/Sig_475_455.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/stop500.json            $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json
 mergeJSONs $JSON_PATH/stop525.json            $JSON_PATH/Orig/SignalPoints/Sig_525_445.json $JSON_PATH/Orig/SignalPoints/Sig_525_455.json $JSON_PATH/Orig/SignalPoints/Sig_525_465.json $JSON_PATH/Orig/SignalPoints/Sig_525_475.json $JSON_PATH/Orig/SignalPoints/Sig_525_485.json $JSON_PATH/Orig/SignalPoints/Sig_525_495.json $JSON_PATH/Orig/SignalPoints/Sig_525_505.json $JSON_PATH/Orig/SignalPoints/Sig_525_515.json
 mergeJSONs $JSON_PATH/stop550.json            $JSON_PATH/Orig/SignalPoints/Sig_550_470.json $JSON_PATH/Orig/SignalPoints/Sig_550_480.json $JSON_PATH/Orig/SignalPoints/Sig_550_490.json $JSON_PATH/Orig/SignalPoints/Sig_550_500.json $JSON_PATH/Orig/SignalPoints/Sig_550_510.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json $JSON_PATH/Orig/SignalPoints/Sig_550_530.json $JSON_PATH/Orig/SignalPoints/Sig_550_540.json
 mergeJSONs $JSON_PATH/stop575.json            $JSON_PATH/Orig/SignalPoints/Sig_575_495.json $JSON_PATH/Orig/SignalPoints/Sig_575_505.json $JSON_PATH/Orig/SignalPoints/Sig_575_515.json $JSON_PATH/Orig/SignalPoints/Sig_575_525.json $JSON_PATH/Orig/SignalPoints/Sig_575_535.json $JSON_PATH/Orig/SignalPoints/Sig_575_545.json $JSON_PATH/Orig/SignalPoints/Sig_575_555.json $JSON_PATH/Orig/SignalPoints/Sig_575_565.json
 mergeJSONs $JSON_PATH/stop600.json            $JSON_PATH/Orig/SignalPoints/Sig_600_520.json $JSON_PATH/Orig/SignalPoints/Sig_600_530.json $JSON_PATH/Orig/SignalPoints/Sig_600_540.json $JSON_PATH/Orig/SignalPoints/Sig_600_550.json $JSON_PATH/Orig/SignalPoints/Sig_600_560.json $JSON_PATH/Orig/SignalPoints/Sig_600_570.json $JSON_PATH/Orig/SignalPoints/Sig_600_580.json $JSON_PATH/Orig/SignalPoints/Sig_600_590.json
 mergeJSONs $JSON_PATH/stop625.json            $JSON_PATH/Orig/SignalPoints/Sig_625_545.json $JSON_PATH/Orig/SignalPoints/Sig_625_555.json $JSON_PATH/Orig/SignalPoints/Sig_625_565.json $JSON_PATH/Orig/SignalPoints/Sig_625_575.json $JSON_PATH/Orig/SignalPoints/Sig_625_585.json $JSON_PATH/Orig/SignalPoints/Sig_625_595.json $JSON_PATH/Orig/SignalPoints/Sig_625_605.json $JSON_PATH/Orig/SignalPoints/Sig_625_615.json
 mergeJSONs $JSON_PATH/stop650.json            $JSON_PATH/Orig/SignalPoints/Sig_650_570.json $JSON_PATH/Orig/SignalPoints/Sig_650_580.json $JSON_PATH/Orig/SignalPoints/Sig_650_590.json $JSON_PATH/Orig/SignalPoints/Sig_650_600.json $JSON_PATH/Orig/SignalPoints/Sig_650_610.json $JSON_PATH/Orig/SignalPoints/Sig_650_620.json $JSON_PATH/Orig/SignalPoints/Sig_650_630.json $JSON_PATH/Orig/SignalPoints/Sig_650_640.json
 mergeJSONs $JSON_PATH/stop675.json            $JSON_PATH/Orig/SignalPoints/Sig_675_595.json $JSON_PATH/Orig/SignalPoints/Sig_675_605.json $JSON_PATH/Orig/SignalPoints/Sig_675_615.json $JSON_PATH/Orig/SignalPoints/Sig_675_625.json $JSON_PATH/Orig/SignalPoints/Sig_675_635.json $JSON_PATH/Orig/SignalPoints/Sig_675_645.json $JSON_PATH/Orig/SignalPoints/Sig_675_655.json $JSON_PATH/Orig/SignalPoints/Sig_675_665.json
 mergeJSONs $JSON_PATH/stop700.json            $JSON_PATH/Orig/SignalPoints/Sig_700_620.json $JSON_PATH/Orig/SignalPoints/Sig_700_630.json $JSON_PATH/Orig/SignalPoints/Sig_700_640.json $JSON_PATH/Orig/SignalPoints/Sig_700_650.json $JSON_PATH/Orig/SignalPoints/Sig_700_660.json $JSON_PATH/Orig/SignalPoints/Sig_700_670.json $JSON_PATH/Orig/SignalPoints/Sig_700_680.json $JSON_PATH/Orig/SignalPoints/Sig_700_690.json
 mergeJSONs $JSON_PATH/stop725.json            $JSON_PATH/Orig/SignalPoints/Sig_725_645.json $JSON_PATH/Orig/SignalPoints/Sig_725_655.json $JSON_PATH/Orig/SignalPoints/Sig_725_665.json $JSON_PATH/Orig/SignalPoints/Sig_725_675.json $JSON_PATH/Orig/SignalPoints/Sig_725_685.json $JSON_PATH/Orig/SignalPoints/Sig_725_695.json $JSON_PATH/Orig/SignalPoints/Sig_725_705.json $JSON_PATH/Orig/SignalPoints/Sig_725_715.json
 mergeJSONs $JSON_PATH/stop750.json            $JSON_PATH/Orig/SignalPoints/Sig_750_670.json $JSON_PATH/Orig/SignalPoints/Sig_750_680.json $JSON_PATH/Orig/SignalPoints/Sig_750_690.json $JSON_PATH/Orig/SignalPoints/Sig_750_700.json $JSON_PATH/Orig/SignalPoints/Sig_750_710.json $JSON_PATH/Orig/SignalPoints/Sig_750_720.json $JSON_PATH/Orig/SignalPoints/Sig_750_730.json $JSON_PATH/Orig/SignalPoints/Sig_750_740.json
 mergeJSONs $JSON_PATH/stop775.json            $JSON_PATH/Orig/SignalPoints/Sig_775_695.json $JSON_PATH/Orig/SignalPoints/Sig_775_705.json $JSON_PATH/Orig/SignalPoints/Sig_775_715.json $JSON_PATH/Orig/SignalPoints/Sig_775_725.json $JSON_PATH/Orig/SignalPoints/Sig_775_735.json $JSON_PATH/Orig/SignalPoints/Sig_775_745.json $JSON_PATH/Orig/SignalPoints/Sig_775_755.json $JSON_PATH/Orig/SignalPoints/Sig_775_765.json
 mergeJSONs $JSON_PATH/stop800.json            $JSON_PATH/Orig/SignalPoints/Sig_800_720.json $JSON_PATH/Orig/SignalPoints/Sig_800_730.json $JSON_PATH/Orig/SignalPoints/Sig_800_740.json $JSON_PATH/Orig/SignalPoints/Sig_800_750.json $JSON_PATH/Orig/SignalPoints/Sig_800_760.json $JSON_PATH/Orig/SignalPoints/Sig_800_770.json $JSON_PATH/Orig/SignalPoints/Sig_800_780.json $JSON_PATH/Orig/SignalPoints/Sig_800_790.json

 # Make a json with all samples
 mergeJSONs $JSON_PATH/allSamples.json         $JSON_PATH/allMC.json $JSON_PATH/Orig/Data.json $JSON_PATH/allPD.json $JSON_PATH/Orig/DeltaM.json $JSON_PATH/stop250.json $JSON_PATH/stop275.json $JSON_PATH/stop300.json $JSON_PATH/stop325.json $JSON_PATH/stop350.json $JSON_PATH/stop375.json $JSON_PATH/stop400.json $JSON_PATH/stop425.json $JSON_PATH/stop450.json $JSON_PATH/stop475.json $JSON_PATH/stop500.json $JSON_PATH/stop525.json $JSON_PATH/stop550.json $JSON_PATH/stop575.json $JSON_PATH/stop600.json $JSON_PATH/stop625.json $JSON_PATH/stop650.json $JSON_PATH/stop675.json $JSON_PATH/stop700.json $JSON_PATH/stop725.json $JSON_PATH/stop750.json $JSON_PATH/stop775.json $JSON_PATH/stop800.json
 mergeJSONs $JSON_PATH/allSamplesSwap.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataSingleLepton.json  $JSON_PATH/Orig/DeltaM.json $JSON_PATH/stop250.json $JSON_PATH/stop275.json $JSON_PATH/stop300.json $JSON_PATH/stop325.json $JSON_PATH/stop350.json $JSON_PATH/stop375.json $JSON_PATH/stop400.json $JSON_PATH/stop425.json $JSON_PATH/stop450.json $JSON_PATH/stop475.json $JSON_PATH/stop500.json $JSON_PATH/stop525.json $JSON_PATH/stop550.json $JSON_PATH/stop575.json $JSON_PATH/stop600.json $JSON_PATH/stop625.json $JSON_PATH/stop650.json $JSON_PATH/stop675.json $JSON_PATH/stop700.json $JSON_PATH/stop725.json $JSON_PATH/stop750.json $JSON_PATH/stop775.json $JSON_PATH/stop800.json

 mergeJSONs $JSON_PATH/allSamplesQuick.json    $JSON_PATH/allMCQuick.json $JSON_PATH/Orig/Data.json
 #$JSON_PATH/stop250.json $JSON_PATH/stop275.json $JSON_PATH/stop300.json $JSON_PATH/stop325.json $JSON_PATH/stop350.json $JSON_PATH/stop375.json $JSON_PATH/stop400.json $JSON_PATH/stop425.json $JSON_PATH/stop450.json $JSON_PATH/stop475.json $JSON_PATH/stop500.json $JSON_PATH/stop525.json $JSON_PATH/stop550.json $JSON_PATH/stop575.json $JSON_PATH/stop600.json $JSON_PATH/stop625.json $JSON_PATH/stop650.json $JSON_PATH/stop675.json $JSON_PATH/stop700.json $JSON_PATH/stop725.json $JSON_PATH/stop750.json $JSON_PATH/stop775.json $JSON_PATH/stop800.json
 # $JSON_PATH/Orig/DeltaM.json

 mergeJSONs $JSON_PATH/4Pedrame.json  $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/TTLep.json

elif [ ${YEAR} == 2016 ] || [ ${YEAR} == 2017 ] || [ ${YEAR} == 2018 ]; then
 # Test VV process with new heppy tuples
 #cp         $JSON_PATH/Orig/VV.json               $JSON_PATH/VV.json
 # Make a JSON for all MC except signal
 #mergeJSONs $JSON_PATH/Orig/Wjets.json               $JSON_PATH/Orig/W_*Jets*.json
 #mergeJSONs $JSON_PATH/Orig/ZInv.json                $JSON_PATH/Orig/ZJetsToNuNu*.json
 #cp         $JSON_PATH/Orig/TTbar_madgraph.json      $JSON_PATH/TTbar.json
 cp         $JSON_PATH/Orig/TTbar.json               $JSON_PATH/TTbar.json
 cp         $JSON_PATH/Orig/WJets.json               $JSON_PATH/Wjets.json
 cp         $JSON_PATH/Orig/ZInv.json                $JSON_PATH/ZInv.json
 mergeJSONs $JSON_PATH/ttX.json                      $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTW_LO.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTZToLLNuNu.json
 mergeJSONs $JSON_PATH/otherMC1.json                 $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/DYJets.json
 mergeJSONs $JSON_PATH/otherMC2.json                 $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/QCD.json $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTW_LO.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTZToLLNuNu.json
 mergeJSONs $JSON_PATH/tmpMC.json                    $JSON_PATH/TTbar.json $JSON_PATH/Wjets.json $JSON_PATH/ZInv.json $JSON_PATH/otherMC1.json
 mergeJSONs $JSON_PATH/QCD_en.json                   $JSON_PATH/Orig/QCD_EM.json $JSON_PATH/Orig/QCD_Mu.json
 cp         $JSON_PATH/Orig/WNJets.json               $JSON_PATH/WNJets.json
 cp         $JSON_PATH/Orig/WJetsNLO.json               $JSON_PATH/WJetsNLO.json

 mergeJSONs $JSON_PATH/allMC.json                    $JSON_PATH/ttX.json $JSON_PATH/Orig/QCD.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/WJetsNLO.json
 mergeJSONs $JSON_PATH/allMC_LO.json                    $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Wjets.json
 mergeJSONs $JSON_PATH/allMC-QCD-en.json             $JSON_PATH/QCD_en.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Wjets.json

 mergeJSONs $JSON_PATH/allMC_pow.json                $JSON_PATH/ttX.json $JSON_PATH/Orig/QCD.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/Orig/TTbar_pow.json $JSON_PATH/WJetsNLO.json

 mergeJSONs $JSON_PATH/allMC_HT_pow.json                    $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/Orig/TTbar_pow.json $JSON_PATH/Orig/WJetsHT.json

 mergeJSONs $JSON_PATH/otherMC2_QCD_Mu_en.json                 $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/QCD_Mu.json $JSON_PATH/Orig/TTGJets.json $JSON_PATH/Orig/TTW_LO.json $JSON_PATH/Orig/TTWToLNu.json $JSON_PATH/Orig/TTZToLLNuNu.json

 mergeJSONs $JSON_PATH/allMC_QCD_Mu_en.json                 $JSON_PATH/Orig/QCD_Mu.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Wjets.json

 #Make a JSON with the samples that are to be processed:
 cp         $JSON_PATH/allMC.json                    $JSON_PATH/MC2Process.json
 cp         $JSON_PATH/allMC_LO.json                    $JSON_PATH/MC2Process_LO.json

 # Copy the data JSON over, so that all locations are consistent
 cp         $JSON_PATH/Orig/DataJetHT.json           $JSON_PATH/DataJetHT.json
 cp         $JSON_PATH/Orig/DataMetHT.json           $JSON_PATH/DataMetHT.json
 cp         $JSON_PATH/Orig/DataSingleElectron.json  $JSON_PATH/DataSingleElectron.json
 cp         $JSON_PATH/Orig/DataSingleMuon.json      $JSON_PATH/DataSingleMuon.json
 mergeJSONs $JSON_PATH/analysisData.json             $JSON_PATH/Orig/DataJetHT.json $JSON_PATH/Orig/DataMetHT.json
 mergeJSONs $JSON_PATH/allData.json                  $JSON_PATH/Orig/DataJetHT.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/DataSingleElectron.json $JSON_PATH/Orig/DataSingleMuon.json
 #mergeJSONs $JSON_PATH/DataLepton.json         $JSON_PATH/Orig/DataSingleElectron.json $JSON_PATH/Orig/DataSingleMuon.json

 # Copy the JSON with the info for each deltaM over, so that all locations are consistent
 cp         $JSON_PATH/Orig/DeltaM.json        $JSON_PATH/

 # Make a JSON for each group of signal points with the same stop mass
 mergeJSONs $JSON_PATH/stop250.json            $JSON_PATH/Orig/SignalPoints/Sig_250_170.json $JSON_PATH/Orig/SignalPoints/Sig_250_180.json $JSON_PATH/Orig/SignalPoints/Sig_250_190.json $JSON_PATH/Orig/SignalPoints/Sig_250_200.json $JSON_PATH/Orig/SignalPoints/Sig_250_210.json $JSON_PATH/Orig/SignalPoints/Sig_250_220.json $JSON_PATH/Orig/SignalPoints/Sig_250_230.json $JSON_PATH/Orig/SignalPoints/Sig_250_240.json
 mergeJSONs $JSON_PATH/stop275.json            $JSON_PATH/Orig/SignalPoints/Sig_275_195.json $JSON_PATH/Orig/SignalPoints/Sig_275_205.json $JSON_PATH/Orig/SignalPoints/Sig_275_215.json $JSON_PATH/Orig/SignalPoints/Sig_275_225.json $JSON_PATH/Orig/SignalPoints/Sig_275_235.json $JSON_PATH/Orig/SignalPoints/Sig_275_245.json $JSON_PATH/Orig/SignalPoints/Sig_275_255.json $JSON_PATH/Orig/SignalPoints/Sig_275_265.json
 mergeJSONs $JSON_PATH/stop300.json            $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json
 mergeJSONs $JSON_PATH/stop325.json            $JSON_PATH/Orig/SignalPoints/Sig_325_245.json $JSON_PATH/Orig/SignalPoints/Sig_325_255.json $JSON_PATH/Orig/SignalPoints/Sig_325_265.json $JSON_PATH/Orig/SignalPoints/Sig_325_275.json $JSON_PATH/Orig/SignalPoints/Sig_325_285.json $JSON_PATH/Orig/SignalPoints/Sig_325_295.json $JSON_PATH/Orig/SignalPoints/Sig_325_305.json $JSON_PATH/Orig/SignalPoints/Sig_325_315.json
 mergeJSONs $JSON_PATH/stop350.json            $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json
 mergeJSONs $JSON_PATH/stop375.json            $JSON_PATH/Orig/SignalPoints/Sig_375_295.json $JSON_PATH/Orig/SignalPoints/Sig_375_305.json $JSON_PATH/Orig/SignalPoints/Sig_375_315.json $JSON_PATH/Orig/SignalPoints/Sig_375_325.json $JSON_PATH/Orig/SignalPoints/Sig_375_335.json $JSON_PATH/Orig/SignalPoints/Sig_375_345.json $JSON_PATH/Orig/SignalPoints/Sig_375_355.json $JSON_PATH/Orig/SignalPoints/Sig_375_365.json
 mergeJSONs $JSON_PATH/stop400.json            $JSON_PATH/Orig/SignalPoints/Sig_400_320.json $JSON_PATH/Orig/SignalPoints/Sig_400_330.json $JSON_PATH/Orig/SignalPoints/Sig_400_340.json $JSON_PATH/Orig/SignalPoints/Sig_400_350.json $JSON_PATH/Orig/SignalPoints/Sig_400_360.json $JSON_PATH/Orig/SignalPoints/Sig_400_370.json $JSON_PATH/Orig/SignalPoints/Sig_400_380.json $JSON_PATH/Orig/SignalPoints/Sig_400_390.json
 mergeJSONs $JSON_PATH/stop425.json            $JSON_PATH/Orig/SignalPoints/Sig_425_345.json $JSON_PATH/Orig/SignalPoints/Sig_425_355.json $JSON_PATH/Orig/SignalPoints/Sig_425_365.json $JSON_PATH/Orig/SignalPoints/Sig_425_375.json $JSON_PATH/Orig/SignalPoints/Sig_425_385.json $JSON_PATH/Orig/SignalPoints/Sig_425_395.json $JSON_PATH/Orig/SignalPoints/Sig_425_405.json $JSON_PATH/Orig/SignalPoints/Sig_425_415.json
 mergeJSONs $JSON_PATH/stop450.json            $JSON_PATH/Orig/SignalPoints/Sig_450_370.json $JSON_PATH/Orig/SignalPoints/Sig_450_380.json $JSON_PATH/Orig/SignalPoints/Sig_450_390.json $JSON_PATH/Orig/SignalPoints/Sig_450_400.json $JSON_PATH/Orig/SignalPoints/Sig_450_410.json $JSON_PATH/Orig/SignalPoints/Sig_450_420.json $JSON_PATH/Orig/SignalPoints/Sig_450_430.json $JSON_PATH/Orig/SignalPoints/Sig_450_440.json
 mergeJSONs $JSON_PATH/stop475.json            $JSON_PATH/Orig/SignalPoints/Sig_475_395.json $JSON_PATH/Orig/SignalPoints/Sig_475_405.json $JSON_PATH/Orig/SignalPoints/Sig_475_415.json $JSON_PATH/Orig/SignalPoints/Sig_475_425.json $JSON_PATH/Orig/SignalPoints/Sig_475_435.json $JSON_PATH/Orig/SignalPoints/Sig_475_445.json $JSON_PATH/Orig/SignalPoints/Sig_475_455.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/stop500.json            $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json
 mergeJSONs $JSON_PATH/stop525.json            $JSON_PATH/Orig/SignalPoints/Sig_526_445.json $JSON_PATH/Orig/SignalPoints/Sig_526_455.json $JSON_PATH/Orig/SignalPoints/Sig_526_465.json $JSON_PATH/Orig/SignalPoints/Sig_526_475.json $JSON_PATH/Orig/SignalPoints/Sig_526_485.json $JSON_PATH/Orig/SignalPoints/Sig_526_495.json $JSON_PATH/Orig/SignalPoints/Sig_526_505.json $JSON_PATH/Orig/SignalPoints/Sig_526_516.json
 mergeJSONs $JSON_PATH/stop550.json            $JSON_PATH/Orig/SignalPoints/Sig_550_470.json $JSON_PATH/Orig/SignalPoints/Sig_550_480.json $JSON_PATH/Orig/SignalPoints/Sig_550_490.json $JSON_PATH/Orig/SignalPoints/Sig_550_500.json $JSON_PATH/Orig/SignalPoints/Sig_550_510.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json $JSON_PATH/Orig/SignalPoints/Sig_550_530.json $JSON_PATH/Orig/SignalPoints/Sig_550_540.json
 mergeJSONs $JSON_PATH/stop575.json            $JSON_PATH/Orig/SignalPoints/Sig_576_495.json $JSON_PATH/Orig/SignalPoints/Sig_576_505.json $JSON_PATH/Orig/SignalPoints/Sig_576_516.json $JSON_PATH/Orig/SignalPoints/Sig_576_526.json $JSON_PATH/Orig/SignalPoints/Sig_576_536.json $JSON_PATH/Orig/SignalPoints/Sig_576_546.json $JSON_PATH/Orig/SignalPoints/Sig_576_556.json $JSON_PATH/Orig/SignalPoints/Sig_576_566.json
 mergeJSONs $JSON_PATH/stop600.json            $JSON_PATH/Orig/SignalPoints/Sig_600_520.json $JSON_PATH/Orig/SignalPoints/Sig_600_530.json $JSON_PATH/Orig/SignalPoints/Sig_600_540.json $JSON_PATH/Orig/SignalPoints/Sig_600_550.json $JSON_PATH/Orig/SignalPoints/Sig_600_560.json $JSON_PATH/Orig/SignalPoints/Sig_600_570.json $JSON_PATH/Orig/SignalPoints/Sig_600_580.json $JSON_PATH/Orig/SignalPoints/Sig_600_590.json
 mergeJSONs $JSON_PATH/stop625.json            $JSON_PATH/Orig/SignalPoints/Sig_626_546.json $JSON_PATH/Orig/SignalPoints/Sig_626_556.json $JSON_PATH/Orig/SignalPoints/Sig_626_566.json $JSON_PATH/Orig/SignalPoints/Sig_626_576.json $JSON_PATH/Orig/SignalPoints/Sig_626_586.json $JSON_PATH/Orig/SignalPoints/Sig_626_596.json $JSON_PATH/Orig/SignalPoints/Sig_626_606.json $JSON_PATH/Orig/SignalPoints/Sig_626_616.json
 mergeJSONs $JSON_PATH/stop650.json            $JSON_PATH/Orig/SignalPoints/Sig_650_570.json $JSON_PATH/Orig/SignalPoints/Sig_650_580.json $JSON_PATH/Orig/SignalPoints/Sig_650_590.json $JSON_PATH/Orig/SignalPoints/Sig_650_600.json $JSON_PATH/Orig/SignalPoints/Sig_650_610.json $JSON_PATH/Orig/SignalPoints/Sig_650_620.json $JSON_PATH/Orig/SignalPoints/Sig_650_630.json $JSON_PATH/Orig/SignalPoints/Sig_650_640.json
 mergeJSONs $JSON_PATH/stop675.json            $JSON_PATH/Orig/SignalPoints/Sig_676_596.json $JSON_PATH/Orig/SignalPoints/Sig_676_606.json $JSON_PATH/Orig/SignalPoints/Sig_676_616.json $JSON_PATH/Orig/SignalPoints/Sig_676_626.json $JSON_PATH/Orig/SignalPoints/Sig_676_636.json $JSON_PATH/Orig/SignalPoints/Sig_676_646.json $JSON_PATH/Orig/SignalPoints/Sig_676_656.json $JSON_PATH/Orig/SignalPoints/Sig_676_666.json
 mergeJSONs $JSON_PATH/stop700.json            $JSON_PATH/Orig/SignalPoints/Sig_700_620.json $JSON_PATH/Orig/SignalPoints/Sig_700_630.json $JSON_PATH/Orig/SignalPoints/Sig_700_640.json $JSON_PATH/Orig/SignalPoints/Sig_700_650.json $JSON_PATH/Orig/SignalPoints/Sig_700_660.json $JSON_PATH/Orig/SignalPoints/Sig_700_670.json $JSON_PATH/Orig/SignalPoints/Sig_700_680.json $JSON_PATH/Orig/SignalPoints/Sig_700_690.json
 mergeJSONs $JSON_PATH/stop725.json            $JSON_PATH/Orig/SignalPoints/Sig_726_646.json $JSON_PATH/Orig/SignalPoints/Sig_726_656.json $JSON_PATH/Orig/SignalPoints/Sig_726_666.json $JSON_PATH/Orig/SignalPoints/Sig_726_676.json $JSON_PATH/Orig/SignalPoints/Sig_726_686.json $JSON_PATH/Orig/SignalPoints/Sig_726_696.json $JSON_PATH/Orig/SignalPoints/Sig_726_706.json $JSON_PATH/Orig/SignalPoints/Sig_726_716.json
 mergeJSONs $JSON_PATH/stop750.json            $JSON_PATH/Orig/SignalPoints/Sig_750_670.json $JSON_PATH/Orig/SignalPoints/Sig_750_680.json $JSON_PATH/Orig/SignalPoints/Sig_750_690.json $JSON_PATH/Orig/SignalPoints/Sig_750_700.json $JSON_PATH/Orig/SignalPoints/Sig_750_710.json $JSON_PATH/Orig/SignalPoints/Sig_750_720.json $JSON_PATH/Orig/SignalPoints/Sig_750_730.json $JSON_PATH/Orig/SignalPoints/Sig_750_740.json
 mergeJSONs $JSON_PATH/stop775.json            $JSON_PATH/Orig/SignalPoints/Sig_776_696.json $JSON_PATH/Orig/SignalPoints/Sig_776_706.json $JSON_PATH/Orig/SignalPoints/Sig_776_716.json $JSON_PATH/Orig/SignalPoints/Sig_776_726.json $JSON_PATH/Orig/SignalPoints/Sig_776_736.json $JSON_PATH/Orig/SignalPoints/Sig_776_746.json $JSON_PATH/Orig/SignalPoints/Sig_776_756.json $JSON_PATH/Orig/SignalPoints/Sig_776_766.json
 mergeJSONs $JSON_PATH/stop800.json            $JSON_PATH/Orig/SignalPoints/Sig_800_720.json $JSON_PATH/Orig/SignalPoints/Sig_800_730.json $JSON_PATH/Orig/SignalPoints/Sig_800_740.json $JSON_PATH/Orig/SignalPoints/Sig_800_750.json $JSON_PATH/Orig/SignalPoints/Sig_800_760.json $JSON_PATH/Orig/SignalPoints/Sig_800_770.json $JSON_PATH/Orig/SignalPoints/Sig_800_780.json $JSON_PATH/Orig/SignalPoints/Sig_800_790.json
 mergeJSONs $JSON_PATH/stop825.json            $JSON_PATH/Orig/SignalPoints/Sig_826_746.json  $JSON_PATH/Orig/SignalPoints/Sig_826_766.json  $JSON_PATH/Orig/SignalPoints/Sig_826_786.json  $JSON_PATH/Orig/SignalPoints/Sig_826_806.json $JSON_PATH/Orig/SignalPoints/Sig_826_756.json  $JSON_PATH/Orig/SignalPoints/Sig_826_776.json  $JSON_PATH/Orig/SignalPoints/Sig_826_796.json  $JSON_PATH/Orig/SignalPoints/Sig_826_816.json
 mergeJSONs $JSON_PATH/stop850.json $JSON_PATH/Orig/SignalPoints/Sig_850_770.json $JSON_PATH/Orig/SignalPoints/Sig_850_790.json $JSON_PATH/Orig/SignalPoints/Sig_850_810.json $JSON_PATH/Orig/SignalPoints/Sig_850_830.json $JSON_PATH/Orig/SignalPoints/Sig_850_780.json $JSON_PATH/Orig/SignalPoints/Sig_850_800.json $JSON_PATH/Orig/SignalPoints/Sig_850_820.json $JSON_PATH/Orig/SignalPoints/Sig_850_840.json
 mergeJSONs $JSON_PATH/stop875.json $JSON_PATH/Orig/SignalPoints/Sig_876_796.json $JSON_PATH/Orig/SignalPoints/Sig_876_816.json $JSON_PATH/Orig/SignalPoints/Sig_876_836.json $JSON_PATH/Orig/SignalPoints/Sig_876_856.json $JSON_PATH/Orig/SignalPoints/Sig_876_806.json $JSON_PATH/Orig/SignalPoints/Sig_876_826.json $JSON_PATH/Orig/SignalPoints/Sig_876_846.json $JSON_PATH/Orig/SignalPoints/Sig_876_866.json
 mergeJSONs $JSON_PATH/stop900.json $JSON_PATH/Orig/SignalPoints/Sig_900_820.json $JSON_PATH/Orig/SignalPoints/Sig_900_840.json $JSON_PATH/Orig/SignalPoints/Sig_900_860.json $JSON_PATH/Orig/SignalPoints/Sig_900_880.json $JSON_PATH/Orig/SignalPoints/Sig_900_830.json $JSON_PATH/Orig/SignalPoints/Sig_900_850.json $JSON_PATH/Orig/SignalPoints/Sig_900_870.json $JSON_PATH/Orig/SignalPoints/Sig_900_890.json
 mergeJSONs $JSON_PATH/stop925.json $JSON_PATH/Orig/SignalPoints/Sig_926_846.json $JSON_PATH/Orig/SignalPoints/Sig_926_866.json $JSON_PATH/Orig/SignalPoints/Sig_926_886.json $JSON_PATH/Orig/SignalPoints/Sig_926_906.json $JSON_PATH/Orig/SignalPoints/Sig_926_856.json $JSON_PATH/Orig/SignalPoints/Sig_926_876.json $JSON_PATH/Orig/SignalPoints/Sig_926_896.json $JSON_PATH/Orig/SignalPoints/Sig_926_916.json
 mergeJSONs $JSON_PATH/stop950.json $JSON_PATH/Orig/SignalPoints/Sig_950_870.json $JSON_PATH/Orig/SignalPoints/Sig_950_890.json $JSON_PATH/Orig/SignalPoints/Sig_950_910.json $JSON_PATH/Orig/SignalPoints/Sig_950_930.json $JSON_PATH/Orig/SignalPoints/Sig_950_880.json $JSON_PATH/Orig/SignalPoints/Sig_950_900.json $JSON_PATH/Orig/SignalPoints/Sig_950_920.json $JSON_PATH/Orig/SignalPoints/Sig_950_940.json
 mergeJSONs $JSON_PATH/stop975.json $JSON_PATH/Orig/SignalPoints/Sig_976_896.json $JSON_PATH/Orig/SignalPoints/Sig_976_916.json $JSON_PATH/Orig/SignalPoints/Sig_976_936.json $JSON_PATH/Orig/SignalPoints/Sig_976_956.json $JSON_PATH/Orig/SignalPoints/Sig_976_906.json $JSON_PATH/Orig/SignalPoints/Sig_976_926.json $JSON_PATH/Orig/SignalPoints/Sig_976_946.json $JSON_PATH/Orig/SignalPoints/Sig_976_966.json
 mergeJSONs $JSON_PATH/stop1000.json $JSON_PATH/Orig/SignalPoints/Sig_1000_920.json $JSON_PATH/Orig/SignalPoints/Sig_1000_940.json $JSON_PATH/Orig/SignalPoints/Sig_1000_960.json $JSON_PATH/Orig/SignalPoints/Sig_1000_980.json $JSON_PATH/Orig/SignalPoints/Sig_1000_930.json $JSON_PATH/Orig/SignalPoints/Sig_1000_950.json $JSON_PATH/Orig/SignalPoints/Sig_1000_970.json $JSON_PATH/Orig/SignalPoints/Sig_1000_990.json
 mergeJSONs $JSON_PATH/stop1025.json $JSON_PATH/Orig/SignalPoints/Sig_1024_1006.json $JSON_PATH/Orig/SignalPoints/Sig_1024_946.json  $JSON_PATH/Orig/SignalPoints/Sig_1024_966.json  $JSON_PATH/Orig/SignalPoints/Sig_1024_986.json $JSON_PATH/Orig/SignalPoints/Sig_1024_1016.json $JSON_PATH/Orig/SignalPoints/Sig_1024_956.json  $JSON_PATH/Orig/SignalPoints/Sig_1024_976.json  $JSON_PATH/Orig/SignalPoints/Sig_1024_996.json
 mergeJSONs $JSON_PATH/stop1050.json $JSON_PATH/Orig/SignalPoints/Sig_1052_1000.json $JSON_PATH/Orig/SignalPoints/Sig_1052_1020.json $JSON_PATH/Orig/SignalPoints/Sig_1052_1040.json $JSON_PATH/Orig/SignalPoints/Sig_1052_980.json $JSON_PATH/Orig/SignalPoints/Sig_1052_1010.json $JSON_PATH/Orig/SignalPoints/Sig_1052_1032.json $JSON_PATH/Orig/SignalPoints/Sig_1052_970.json  $JSON_PATH/Orig/SignalPoints/Sig_1052_990.json
 mergeJSONs $JSON_PATH/stop1075.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1006.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1024.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1044.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1064.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1016.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1036.json $JSON_PATH/Orig/SignalPoints/Sig_1076_1056.json $JSON_PATH/Orig/SignalPoints/Sig_1076_996.json
 mergeJSONs $JSON_PATH/stop1100.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1020.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1040.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1060.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1080.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1032.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1052.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1072.json $JSON_PATH/Orig/SignalPoints/Sig_1100_1092.json

 mergeJSONs $JSON_PATH/ANSignals.json $JSON_PATH/stop250.json $JSON_PATH/stop275.json $JSON_PATH/stop300.json $JSON_PATH/stop325.json $JSON_PATH/stop350.json $JSON_PATH/stop375.json $JSON_PATH/stop400.json $JSON_PATH/stop425.json $JSON_PATH/stop450.json $JSON_PATH/stop475.json $JSON_PATH/stop500.json $JSON_PATH/stop525.json $JSON_PATH/stop550.json $JSON_PATH/stop575.json $JSON_PATH/stop600.json $JSON_PATH/stop625.json $JSON_PATH/stop650.json $JSON_PATH/stop675.json $JSON_PATH/stop700.json $JSON_PATH/stop725.json $JSON_PATH/stop750.json $JSON_PATH/stop775.json $JSON_PATH/stop800.json

 mergeJSONs $JSON_PATH/AllSignals.json $JSON_PATH/stop250.json $JSON_PATH/stop275.json $JSON_PATH/stop300.json $JSON_PATH/stop325.json $JSON_PATH/stop350.json $JSON_PATH/stop375.json $JSON_PATH/stop400.json $JSON_PATH/stop425.json $JSON_PATH/stop450.json $JSON_PATH/stop475.json $JSON_PATH/stop500.json $JSON_PATH/stop525.json $JSON_PATH/stop550.json $JSON_PATH/stop575.json $JSON_PATH/stop600.json $JSON_PATH/stop625.json $JSON_PATH/stop650.json $JSON_PATH/stop675.json $JSON_PATH/stop700.json $JSON_PATH/stop725.json $JSON_PATH/stop750.json $JSON_PATH/stop775.json $JSON_PATH/stop800.json $JSON_PATH/stop825.json $JSON_PATH/stop850.json $JSON_PATH/stop875.json $JSON_PATH/stop900.json $JSON_PATH/stop925.json $JSON_PATH/stop950.json $JSON_PATH/stop975.json $JSON_PATH/stop1000.json $JSON_PATH/stop1025.json $JSON_PATH/stop1050.json $JSON_PATH/stop1075.json $JSON_PATH/stop1100.json

 mergeJSONs $JSON_PATH/stop_deltaM10.json $JSON_PATH/Orig/SignalPoints/Sig_250_240.json $JSON_PATH/Orig/SignalPoints/Sig_275_265.json $JSON_PATH/Orig/SignalPoints/Sig_300_290.json $JSON_PATH/Orig/SignalPoints/Sig_325_315.json $JSON_PATH/Orig/SignalPoints/Sig_350_340.json $JSON_PATH/Orig/SignalPoints/Sig_375_365.json $JSON_PATH/Orig/SignalPoints/Sig_400_390.json $JSON_PATH/Orig/SignalPoints/Sig_425_415.json $JSON_PATH/Orig/SignalPoints/Sig_450_440.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json $JSON_PATH/Orig/SignalPoints/Sig_526_516.json $JSON_PATH/Orig/SignalPoints/Sig_550_540.json $JSON_PATH/Orig/SignalPoints/Sig_576_566.json $JSON_PATH/Orig/SignalPoints/Sig_600_590.json $JSON_PATH/Orig/SignalPoints/Sig_626_616.json $JSON_PATH/Orig/SignalPoints/Sig_650_640.json $JSON_PATH/Orig/SignalPoints/Sig_676_666.json $JSON_PATH/Orig/SignalPoints/Sig_700_690.json $JSON_PATH/Orig/SignalPoints/Sig_726_716.json $JSON_PATH/Orig/SignalPoints/Sig_750_740.json $JSON_PATH/Orig/SignalPoints/Sig_776_766.json $JSON_PATH/Orig/SignalPoints/Sig_800_790.json 

 mergeJSONs $JSON_PATH/stop_deltaM20.json $JSON_PATH/Orig/SignalPoints/Sig_250_230.json $JSON_PATH/Orig/SignalPoints/Sig_275_255.json $JSON_PATH/Orig/SignalPoints/Sig_300_280.json $JSON_PATH/Orig/SignalPoints/Sig_325_305.json $JSON_PATH/Orig/SignalPoints/Sig_350_330.json $JSON_PATH/Orig/SignalPoints/Sig_375_355.json $JSON_PATH/Orig/SignalPoints/Sig_400_380.json $JSON_PATH/Orig/SignalPoints/Sig_425_405.json $JSON_PATH/Orig/SignalPoints/Sig_450_430.json $JSON_PATH/Orig/SignalPoints/Sig_475_455.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json $JSON_PATH/Orig/SignalPoints/Sig_526_505.json $JSON_PATH/Orig/SignalPoints/Sig_550_530.json $JSON_PATH/Orig/SignalPoints/Sig_576_556.json $JSON_PATH/Orig/SignalPoints/Sig_600_580.json $JSON_PATH/Orig/SignalPoints/Sig_626_606.json $JSON_PATH/Orig/SignalPoints/Sig_650_630.json $JSON_PATH/Orig/SignalPoints/Sig_676_656.json $JSON_PATH/Orig/SignalPoints/Sig_700_680.json $JSON_PATH/Orig/SignalPoints/Sig_726_706.json $JSON_PATH/Orig/SignalPoints/Sig_750_730.json $JSON_PATH/Orig/SignalPoints/Sig_776_756.json $JSON_PATH/Orig/SignalPoints/Sig_800_780.json
 mergeJSONs $JSON_PATH/stop_deltaM30.json $JSON_PATH/Orig/SignalPoints/Sig_250_220.json $JSON_PATH/Orig/SignalPoints/Sig_275_245.json $JSON_PATH/Orig/SignalPoints/Sig_300_270.json $JSON_PATH/Orig/SignalPoints/Sig_325_295.json $JSON_PATH/Orig/SignalPoints/Sig_350_320.json $JSON_PATH/Orig/SignalPoints/Sig_375_345.json $JSON_PATH/Orig/SignalPoints/Sig_400_370.json $JSON_PATH/Orig/SignalPoints/Sig_425_395.json $JSON_PATH/Orig/SignalPoints/Sig_450_420.json $JSON_PATH/Orig/SignalPoints/Sig_475_445.json $JSON_PATH/Orig/SignalPoints/Sig_500_470.json $JSON_PATH/Orig/SignalPoints/Sig_526_495.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json $JSON_PATH/Orig/SignalPoints/Sig_576_546.json $JSON_PATH/Orig/SignalPoints/Sig_600_570.json $JSON_PATH/Orig/SignalPoints/Sig_626_596.json $JSON_PATH/Orig/SignalPoints/Sig_650_620.json $JSON_PATH/Orig/SignalPoints/Sig_676_646.json $JSON_PATH/Orig/SignalPoints/Sig_700_670.json $JSON_PATH/Orig/SignalPoints/Sig_726_696.json $JSON_PATH/Orig/SignalPoints/Sig_750_720.json $JSON_PATH/Orig/SignalPoints/Sig_776_746.json $JSON_PATH/Orig/SignalPoints/Sig_800_770.json
 mergeJSONs $JSON_PATH/stop_deltaM40.json $JSON_PATH/Orig/SignalPoints/Sig_250_210.json $JSON_PATH/Orig/SignalPoints/Sig_275_235.json $JSON_PATH/Orig/SignalPoints/Sig_300_260.json $JSON_PATH/Orig/SignalPoints/Sig_325_285.json $JSON_PATH/Orig/SignalPoints/Sig_350_310.json $JSON_PATH/Orig/SignalPoints/Sig_375_335.json $JSON_PATH/Orig/SignalPoints/Sig_400_360.json $JSON_PATH/Orig/SignalPoints/Sig_425_385.json $JSON_PATH/Orig/SignalPoints/Sig_450_410.json $JSON_PATH/Orig/SignalPoints/Sig_475_435.json $JSON_PATH/Orig/SignalPoints/Sig_500_460.json $JSON_PATH/Orig/SignalPoints/Sig_526_485.json $JSON_PATH/Orig/SignalPoints/Sig_550_510.json $JSON_PATH/Orig/SignalPoints/Sig_576_536.json $JSON_PATH/Orig/SignalPoints/Sig_600_560.json $JSON_PATH/Orig/SignalPoints/Sig_626_586.json $JSON_PATH/Orig/SignalPoints/Sig_650_610.json $JSON_PATH/Orig/SignalPoints/Sig_676_636.json $JSON_PATH/Orig/SignalPoints/Sig_700_660.json $JSON_PATH/Orig/SignalPoints/Sig_726_686.json $JSON_PATH/Orig/SignalPoints/Sig_750_710.json $JSON_PATH/Orig/SignalPoints/Sig_776_736.json $JSON_PATH/Orig/SignalPoints/Sig_800_760.json
 mergeJSONs $JSON_PATH/stop_deltaM50.json $JSON_PATH/Orig/SignalPoints/Sig_250_200.json $JSON_PATH/Orig/SignalPoints/Sig_275_225.json $JSON_PATH/Orig/SignalPoints/Sig_300_250.json $JSON_PATH/Orig/SignalPoints/Sig_325_275.json $JSON_PATH/Orig/SignalPoints/Sig_350_300.json $JSON_PATH/Orig/SignalPoints/Sig_375_325.json $JSON_PATH/Orig/SignalPoints/Sig_400_350.json $JSON_PATH/Orig/SignalPoints/Sig_425_375.json $JSON_PATH/Orig/SignalPoints/Sig_450_400.json $JSON_PATH/Orig/SignalPoints/Sig_475_425.json $JSON_PATH/Orig/SignalPoints/Sig_500_450.json $JSON_PATH/Orig/SignalPoints/Sig_526_475.json $JSON_PATH/Orig/SignalPoints/Sig_550_500.json $JSON_PATH/Orig/SignalPoints/Sig_576_526.json $JSON_PATH/Orig/SignalPoints/Sig_600_550.json $JSON_PATH/Orig/SignalPoints/Sig_626_576.json $JSON_PATH/Orig/SignalPoints/Sig_650_600.json $JSON_PATH/Orig/SignalPoints/Sig_676_626.json $JSON_PATH/Orig/SignalPoints/Sig_700_650.json $JSON_PATH/Orig/SignalPoints/Sig_726_676.json $JSON_PATH/Orig/SignalPoints/Sig_750_700.json $JSON_PATH/Orig/SignalPoints/Sig_776_726.json $JSON_PATH/Orig/SignalPoints/Sig_800_750.json
 mergeJSONs $JSON_PATH/stop_deltaM60.json $JSON_PATH/Orig/SignalPoints/Sig_250_190.json $JSON_PATH/Orig/SignalPoints/Sig_275_215.json $JSON_PATH/Orig/SignalPoints/Sig_300_240.json $JSON_PATH/Orig/SignalPoints/Sig_325_265.json $JSON_PATH/Orig/SignalPoints/Sig_350_290.json $JSON_PATH/Orig/SignalPoints/Sig_375_315.json $JSON_PATH/Orig/SignalPoints/Sig_400_340.json $JSON_PATH/Orig/SignalPoints/Sig_425_365.json $JSON_PATH/Orig/SignalPoints/Sig_450_390.json $JSON_PATH/Orig/SignalPoints/Sig_475_415.json $JSON_PATH/Orig/SignalPoints/Sig_500_440.json $JSON_PATH/Orig/SignalPoints/Sig_526_465.json $JSON_PATH/Orig/SignalPoints/Sig_550_490.json $JSON_PATH/Orig/SignalPoints/Sig_576_516.json $JSON_PATH/Orig/SignalPoints/Sig_600_540.json $JSON_PATH/Orig/SignalPoints/Sig_626_566.json $JSON_PATH/Orig/SignalPoints/Sig_650_590.json $JSON_PATH/Orig/SignalPoints/Sig_676_616.json $JSON_PATH/Orig/SignalPoints/Sig_700_640.json $JSON_PATH/Orig/SignalPoints/Sig_726_666.json $JSON_PATH/Orig/SignalPoints/Sig_750_690.json $JSON_PATH/Orig/SignalPoints/Sig_776_716.json $JSON_PATH/Orig/SignalPoints/Sig_800_740.json
 mergeJSONs $JSON_PATH/stop_deltaM70.json $JSON_PATH/Orig/SignalPoints/Sig_250_180.json $JSON_PATH/Orig/SignalPoints/Sig_275_205.json $JSON_PATH/Orig/SignalPoints/Sig_300_230.json $JSON_PATH/Orig/SignalPoints/Sig_325_255.json $JSON_PATH/Orig/SignalPoints/Sig_350_280.json $JSON_PATH/Orig/SignalPoints/Sig_375_305.json $JSON_PATH/Orig/SignalPoints/Sig_400_330.json $JSON_PATH/Orig/SignalPoints/Sig_425_355.json $JSON_PATH/Orig/SignalPoints/Sig_450_380.json $JSON_PATH/Orig/SignalPoints/Sig_475_405.json $JSON_PATH/Orig/SignalPoints/Sig_500_430.json $JSON_PATH/Orig/SignalPoints/Sig_526_455.json $JSON_PATH/Orig/SignalPoints/Sig_550_480.json $JSON_PATH/Orig/SignalPoints/Sig_576_505.json $JSON_PATH/Orig/SignalPoints/Sig_600_530.json $JSON_PATH/Orig/SignalPoints/Sig_626_556.json $JSON_PATH/Orig/SignalPoints/Sig_650_580.json $JSON_PATH/Orig/SignalPoints/Sig_676_606.json $JSON_PATH/Orig/SignalPoints/Sig_700_630.json $JSON_PATH/Orig/SignalPoints/Sig_726_656.json $JSON_PATH/Orig/SignalPoints/Sig_750_680.json $JSON_PATH/Orig/SignalPoints/Sig_776_706.json $JSON_PATH/Orig/SignalPoints/Sig_800_730.json
 mergeJSONs $JSON_PATH/stop_deltaM80.json $JSON_PATH/Orig/SignalPoints/Sig_250_170.json $JSON_PATH/Orig/SignalPoints/Sig_275_195.json $JSON_PATH/Orig/SignalPoints/Sig_300_220.json $JSON_PATH/Orig/SignalPoints/Sig_325_245.json $JSON_PATH/Orig/SignalPoints/Sig_350_270.json $JSON_PATH/Orig/SignalPoints/Sig_375_295.json $JSON_PATH/Orig/SignalPoints/Sig_400_320.json $JSON_PATH/Orig/SignalPoints/Sig_425_345.json $JSON_PATH/Orig/SignalPoints/Sig_450_370.json $JSON_PATH/Orig/SignalPoints/Sig_475_395.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_526_445.json $JSON_PATH/Orig/SignalPoints/Sig_550_470.json $JSON_PATH/Orig/SignalPoints/Sig_576_495.json $JSON_PATH/Orig/SignalPoints/Sig_600_520.json $JSON_PATH/Orig/SignalPoints/Sig_626_546.json $JSON_PATH/Orig/SignalPoints/Sig_650_570.json $JSON_PATH/Orig/SignalPoints/Sig_676_596.json $JSON_PATH/Orig/SignalPoints/Sig_700_620.json $JSON_PATH/Orig/SignalPoints/Sig_726_646.json $JSON_PATH/Orig/SignalPoints/Sig_750_670.json $JSON_PATH/Orig/SignalPoints/Sig_776_696.json $JSON_PATH/Orig/SignalPoints/Sig_800_720.json

 # Make a JSON for each group of signal points with the same stop mass for FullSim
# mergeJSONs $JSON_PATH/stop500_FullSim.json            $JSON_PATH/Orig/SignalPoints/Sig_500_420_FullSim.json $JSON_PATH/Orig/SignalPoints/Sig_500_490_FullSim.json

 # Make a JSON for the PU tests
 mergeJSONs $JSON_PATH/puTests.json            $JSON_PATH/Orig/TTbar.json $JSON_PATH/Orig/DataJetHT.json
 # Make the JSONs for plotting
 mergeJSONs $JSON_PATH/plot${YEAR}.json           $JSON_PATH/allMC.json $JSON_PATH/DataMetHT.json
 mergeJSONs $JSON_PATH/plot${YEAR}_pow.json           $JSON_PATH/allMC_pow.json $JSON_PATH/DataMetHT.json
 mergeJSONs $JSON_PATH/plot${YEAR}_QCD_Mu_en.json    $JSON_PATH/allMC_QCD_Mu_en.json $JSON_PATH/DataMetHT.json
 mergeJSONs $JSON_PATH/plot${YEAR}_lep_Sig300_270.json       $JSON_PATH/allMC.json $JSON_PATH/DataMetHT.json         $JSON_PATH/Orig/SignalPoints/Sig_300_270.json
 mergeJSONs $JSON_PATH/plot${YEAR}_lep_Sig250_220.json       $JSON_PATH/allMC.json $JSON_PATH/DataMetHT.json         $JSON_PATH/Orig/SignalPoints/Sig_250_220.json
 mergeJSONs $JSON_PATH/plot${YEAR}_lep_Sig250_170.json       $JSON_PATH/allMC.json $JSON_PATH/DataMetHT.json         $JSON_PATH/Orig/SignalPoints/Sig_250_170.json
 mergeJSONs $JSON_PATH/plot${YEAR}_lep.json       $JSON_PATH/allMC.json $JSON_PATH/DataMetHT.json         $JSON_PATH/stop300.json $JSON_PATH/stop350.json $JSON_PATH/stop500.json

 mergeJSONs $JSON_PATH/plot${YEAR}-QCD-en.json    $JSON_PATH/allMC-QCD-en.json $JSON_PATH/DataMetHT.json
 mergeJSONs $JSON_PATH/plot${YEAR}-inj.json       $JSON_PATH/plot${YEAR}.json $JSON_PATH/stop500.json
 mergeJSONs $JSON_PATH/plot${YEAR}-inj-quick.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/Wjets.json  $JSON_PATH/stop500.json

 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs.json       $JSON_PATH/plot${YEAR}.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json
 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs_pow.json       $JSON_PATH/plot${YEAR}_pow.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json

 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs-WJetsHT-TTpow.json       $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/Orig/TTbar_pow.json $JSON_PATH/Orig/WJetsHT.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json

 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs-WJetsHT.json       $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Orig/WJetsHT.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json

 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs-WNJets.json       $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Orig/WNJets.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json

 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs-WJetsNLO.json       $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Orig/WJetsNLO.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json

 mergeJSONs $JSON_PATH/plot${YEAR}-inj-2SPs-noST.json $JSON_PATH/Orig/QCD.json $JSON_PATH/ttX.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/VV.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Wjets.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/SignalPoints/Sig_500_490.json

 mergeJSONs $JSON_PATH/plot${YEAR}-fake.json      $JSON_PATH/DataJetHT.json $JSON_PATH/ZInv.json $JSON_PATH/Orig/SingleTop.json $JSON_PATH/WJetsNLO.json $JSON_PATH/Orig/VV.json  $JSON_PATH/ttX.json $JSON_PATH/Orig/DYJets.json $JSON_PATH/TTbar.json $JSON_PATH/Orig/QCD.json
 #mergeJSONs $JSON_PATH/plot${YEAR}-fake.json      $JSON_PATH/DataJetHT.json $JSON_PATH/Wjets.json $JSON_PATH/TTbar.json $JSON_PATH/Orig/QCD.json
# mergeJSONs $JSON_PATH/plot${YEAR}_DM10RP_FullSim.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_490_FullSim.json
# mergeJSONs $JSON_PATH/plot${YEAR}_DM80RP_FullSim.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420_FullSim.json

 #mergeJSONs $JSON_PATH/plot${YEAR}_DM10RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM20RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_480.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM30RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM40RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_550_510.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM50RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_526_475.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM60RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_526_465.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM70RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_526_455.json
 #mergeJSONs $JSON_PATH/plot${YEAR}_DM80RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json

 # NEW BENCHMARK POINTS

 mergeJSONs $JSON_PATH/plot${YEAR}_DM10RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM20RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_526_505.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM30RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM40RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_536.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM50RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_526.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM60RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_516.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM70RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_600_530.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM80RP.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_626_546.json

 mergeJSONs $JSON_PATH/plot${YEAR}_DM10RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM20RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_526_505.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM30RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM40RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_536.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM50RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_526.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM60RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_516.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM70RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_600_530.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM80RP_pow.json     $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_626_546.json

 mergeJSONs $JSON_PATH/plot${YEAR}_DM10RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM20RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_526_505.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM30RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM40RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_536.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM50RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_526.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM60RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_576_516.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM70RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_600_530.json
 mergeJSONs $JSON_PATH/plot${YEAR}_DM80RP_HT_pow.json     $JSON_PATH/allMC_HT_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/Orig/SignalPoints/Sig_626_546.json

 mergeJSONs $JSON_PATH/allDM10.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM10.json
 mergeJSONs $JSON_PATH/allDM20.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM20.json
 mergeJSONs $JSON_PATH/allDM30.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM30.json
 mergeJSONs $JSON_PATH/allDM40.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM40.json
 mergeJSONs $JSON_PATH/allDM50.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM50.json
 mergeJSONs $JSON_PATH/allDM60.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM60.json
 mergeJSONs $JSON_PATH/allDM70.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM70.json
 mergeJSONs $JSON_PATH/allDM80.json $JSON_PATH/allMC.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM80.json

 mergeJSONs $JSON_PATH/allDM10_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM10.json
 mergeJSONs $JSON_PATH/allDM20_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM20.json
 mergeJSONs $JSON_PATH/allDM30_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM30.json
 mergeJSONs $JSON_PATH/allDM40_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM40.json
 mergeJSONs $JSON_PATH/allDM50_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM50.json
 mergeJSONs $JSON_PATH/allDM60_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM60.json
 mergeJSONs $JSON_PATH/allDM70_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM70.json
 mergeJSONs $JSON_PATH/allDM80_pow.json $JSON_PATH/allMC_pow.json $JSON_PATH/Orig/DataMetHT.json $JSON_PATH/stop_deltaM80.json

 # For Lepton Studies
 mergeJSONs $JSON_PATH/lepStudies.json     $JSON_PATH/allMC.json $JSON_PATH/Orig/SignalPoints/Sig_475_465.json $JSON_PATH/Orig/SignalPoints/Sig_550_520.json $JSON_PATH/Orig/SignalPoints/Sig_526_465.json $JSON_PATH/Orig/SignalPoints/Sig_500_420.json $JSON_PATH/Orig/DataMetHT.json
 
 # For Raw Closure studies
 mergeJSONs $JSON_PATH/DataAndST.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/SingleTop.json
 mergeJSONs $JSON_PATH/DataAndVV.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/VV.json
 mergeJSONs $JSON_PATH/DataAndTTpow.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/TTbar_pow.json
 mergeJSONs $JSON_PATH/DataAndZInv.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/ZInv.json
  mergeJSONs $JSON_PATH/DataAndWJets.json $JSON_PATH/DataMetHT.json $JSON_PATH/Orig/WJetsNLO.json

fi
